baseURL: "/"
languageCode: "fr-fr"
title: "AfricTivistes"
theme: "hugo-profile"

googleanalytics: UA-xxxxxxx-x
disqusShortname:
Paginate: 3

taxonomies:
  tag: "tags"
  category: "categories"

params:
  favicon: "/images/logo.svg"
  description: "Curateur des Twitters #FreeSenegal"
  copyright: "2021"

  # Navbar Menus
  customMenus:

  # social
  name: "#FreeSenegal"
  github: ""
  linkedin: ""
  twitter: "https://twitter.com/hashtag/FreeSenegal?src=hashtag_click&f=live"
  instagram: ""
  facebook: "https://www.facebook.com/africtivistes"
  twitter: "https://twitter.com/intent/tweet?button_hashtag=TwitterStories"

  # About
  profile_image: "/images/freesenegal.png"
  descripe_l1_person: "La démocratie sénégalaise en danger: Arrestations tous azimuts, Menaces sur les droits humains et sur la liberté de la presse"
  descripe_l2_person: "Suivez l'évolution de la situation avec la curation de #FreeSenegal pour lutter contre les Fakenews."
  useresume: true
  resume: ""

  # Things I do
  usedothings: true
  Things:
    - logo: fa fa-hand-rock
      title: "#FreeSenegal"
      twitters: https://twitter.com/cypher007/lists/freesenegal-18580?ref_src=twsrc%5Etfw
      
    - logo: fa fa-university
      title: "#Kebetu Sénégal"
      twitters: https://twitter.com/cypher007/lists/kebetu?ref_src=twsrc%5Etfw

    - logo: fa fa-globe
      title: "Les Médias"
      twitters: https://twitter.com/cypher007/lists/la-webpolitique?ref_src=twsrc%5Etfw

  #blog ( Description for seo. If you want to show description in your listing or single page, let's make it true)
  showdescription: true

Author:
  name: "AfricTivistes"
  website: "https://www.africtivistes.org"
